enum {
	E_PROP_NONE,

	E_PROP_WHITE_BOX_CLOSED = 1,
	E_PROP_WHITE_BOX_OPEN,

	E_PROP_GREEN_BOX_CLOSED,
	E_PROP_GREEN_BOX_OPEN,

	E_PROP_RED_BOX_CLOSED,
	E_PROP_RED_BOX_OPEN,

	E_PROP_BLUE_BOX_CLOSED,
	E_PROP_BLUE_BOX_OPEN,

	BURGERSHOT_MENU_HEALTHY, //2354
	BURGERSHOT_MENU_LOW, // 2213
	BURGERSHOT_MENU_MED, // 2214
	BURGERSHOT_MENU_HIGH, //2212

	CLUCKINBELL_MENU_HEALTHY, // 2353
	CLUCKINBELL_MENU_LOW, // 2215
	CLUCKINBELL_MENU_MED, // 2216
	CLUCKINBELL_MENU_HIGH, // 2217

	PIZZASTACK_MENU_HEALTHY, // 2355
	PIZZASTACK_MENU_LOW, // 2218
	PIZZASTACK_MENU_MED, // 2219
	PIZZASTACK_MENU_HIGH, // 2220

	DONUTS_MENU_LOW, // 2221
	DONUTS_MENU_MED, // 2222
	DONUTS_MENU_HIGH, // 2223
} ;

enum {
	E_INTERACT_TYPE_FOOD, 
	E_INTERACT_TYPE_DRINK
}

enum E_PROP_ITEM_DATA {

	E_PROP_ITEM_CONST,
	E_PROP_ITEM_DESC [ 32],
	E_PROP_ITEM_MODELID,
	E_PROP_ITEM_EFFECT,
	Float: E_PROP_ITEM_MODIFIER
} ;

enum {

	E_PROP_EFFECT_NONE,
	E_PROP_EFFECT_EAT,
	E_PROP_EFFECT_DRINK
} ;

enum {

	E_PROP_ITEM_NONE,
	E_PROP_ITEM_BOTTLE_YELLOW,
	E_PROP_ITEM_BOTTLE_WHITE,
	E_PROP_ITEM_BOTTLE_GREEN,
	E_PROP_ITEM_BOTTLE_BROWN,
	E_PROP_ITEM_BOTTLE_WHISKY,
	E_PROP_ITEM_BOTTLE_FLASK,

	E_PROP_ITEM_BOTTLE_VODKA,
	E_PROP_ITEM_BOTTLE_CORK,
	E_PROP_ITEM_BOTTLE_RED_WINE,
	E_PROP_ITEM_BOTTLE_WHITE_WINE,

	E_PROP_ITEM_DRINK_COFFEE,
	E_PROP_ITEM_DRINK_BEER_GLASS,
	E_PROP_ITEM_DRINK_WINE_GLASS,
	E_PROP_ITEM_DRINK_MIX_GLASS,
	E_PROP_ITEM_DRINK_SPRUNK_GLASS,
	E_PROP_ITEM_DRINK_SPRUNK_CAN,
	E_PROP_ITEM_DRINK_ECOLA_CAN,
	E_PROP_ITEM_DRINK_SODA_CUP,

	E_PROP_ITEM_FOOD_PIZZA_SLICE,
	E_PROP_ITEM_FOOD_BURGER,
	E_PROP_ITEM_FOOD_CLUCK_WRAP,
	E_PROP_ITEM_FOOD_CAKE_VANILLA,
	E_PROP_ITEM_FOOD_CAKE_CHOCOLATE,
	E_PROP_ITEM_FOOD_CAKE_CREAM,
	E_PROP_ITEM_FOOD_CHICKEN_LEG,
	E_PROP_ITEM_FOOD_STEAK
}

new PropItem [ ] [ E_PROP_ITEM_DATA ] = {

	{ E_PROP_ITEM_NONE , "None", 0, E_PROP_EFFECT_NONE, 0.0 },

	// Bottles
	{  E_PROP_ITEM_BOTTLE_YELLOW, "Yellow Bottle", 1544, E_PROP_EFFECT_DRINK, 4.0  }, // corona
	{  E_PROP_ITEM_BOTTLE_WHITE, "White Bottle", 1484, E_PROP_EFFECT_DRINK, 4.0 }, // fleischberg

	{  E_PROP_ITEM_BOTTLE_GREEN, "Green Bottle", 1486, E_PROP_EFFECT_DRINK, 4.0 }, // malt liquor
	{  E_PROP_ITEM_BOTTLE_BROWN, "Brown Bottle", 1543, E_PROP_EFFECT_DRINK, 4.0 }, // pissch

	{  E_PROP_ITEM_BOTTLE_WHISKY, "Whisky Bottle", 19820, E_PROP_EFFECT_DRINK, 6.0 }, // whisky
	{  E_PROP_ITEM_BOTTLE_FLASK, "Whisky Flask", 19823, E_PROP_EFFECT_DRINK, 6.0 }, // whisky

	{  E_PROP_ITEM_BOTTLE_VODKA, "Vodka Bottle", 19821, E_PROP_EFFECT_DRINK,  5.0 }, // vodka
	{  E_PROP_ITEM_BOTTLE_CORK, "Beer Cork Bottle", 1950, E_PROP_EFFECT_DRINK, 5.0 }, // 40oz

	{  E_PROP_ITEM_BOTTLE_RED_WINE, "Red Wine Bottle", 19822, E_PROP_EFFECT_DRINK, 4.0 }, // wine
	{ E_PROP_ITEM_BOTTLE_WHITE_WINE , "White Wine Bottle", 19824, E_PROP_EFFECT_DRINK, 4.0 }, // wine


	// Cups / Glasses
	{  E_PROP_ITEM_DRINK_COFFEE, "Coffee", 19835, E_PROP_EFFECT_DRINK, 3.5 },

	{  E_PROP_ITEM_DRINK_BEER_GLASS, "Beer Glass", 1666, E_PROP_EFFECT_DRINK, 4.0 },
	{  E_PROP_ITEM_DRINK_WINE_GLASS, "Wine Glass", 19818, E_PROP_EFFECT_DRINK, 4.0 },
	{  E_PROP_ITEM_DRINK_MIX_GLASS, "Cocktail Glass", 19819, E_PROP_EFFECT_DRINK, 5.0 },

	{  E_PROP_ITEM_DRINK_SPRUNK_GLASS, "Sprunk Glass", 1666, E_PROP_EFFECT_DRINK, 2.0 },
	{  E_PROP_ITEM_DRINK_SPRUNK_CAN, "Sprunk Can", E_VENDING_CAN_SPRUNK_SMALL, E_PROP_EFFECT_DRINK, 2.0 }, // make it so all vending machines sell these
	{  E_PROP_ITEM_DRINK_ECOLA_CAN, "E-Cola Can", E_VENDING_CAN_ECOLA_BIG, E_PROP_EFFECT_DRINK, 2.0 }, // make it so all vending machines sell these
	{  E_PROP_ITEM_DRINK_SODA_CUP, "Soda Cup", 2647, E_PROP_EFFECT_DRINK, 2.0 },
	
	// remove all vending machines & recreate custom ones


	{  E_PROP_ITEM_FOOD_PIZZA_SLICE, "Pizza Slice", 2702, E_PROP_EFFECT_EAT, 12.5 },
	{  E_PROP_ITEM_FOOD_BURGER, "Burger", 2703, E_PROP_EFFECT_EAT, 12.5 },
	{  E_PROP_ITEM_FOOD_CLUCK_WRAP, "Cluckin' Wrap", 2769, E_PROP_EFFECT_EAT, 12.5 },

	// For donut menus
	{ E_PROP_ITEM_FOOD_CAKE_VANILLA, "Vanilla Cake", 11740, E_PROP_EFFECT_EAT, 12.5 },
	{ E_PROP_ITEM_FOOD_CAKE_CHOCOLATE, "Chocolate Cake", 11741, E_PROP_EFFECT_EAT, 12.5 },
	{ E_PROP_ITEM_FOOD_CAKE_CREAM, "Cream Cake", 11739, E_PROP_EFFECT_EAT, 12.5 },

	{ E_PROP_ITEM_FOOD_CHICKEN_LEG, "Chicken Leg", 19847, E_PROP_EFFECT_EAT, 12.5 },
	{ E_PROP_ITEM_FOOD_STEAK, "Steak", 19882, E_PROP_EFFECT_EAT, 12.5 }
} ;